logging:
  file: ${spring.application.name}.log
  level:
     root: DEBUG
     com:
        scio: DEBUG
server:
   port: 7992
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8001/eureka/
spring:
   application:
      name: scio-cloud-shardingjdbc
   profiles:
      active: dev
   jpa:
      database-platform: com.scio.cloud.shardingjdbc.config.MySQL5PlusDialect
      generate-ddl: false
      hibernate:
        ddl-auto: none
        use-new-id-generator-mappings: false
      show-sql: true
      properties:
         hibernate:
           format_sql: false
           dialect: com.scio.cloud.shardingjdbc.config.MySQL5PlusDialect

## sharding jdbc properties for java config 
spring.ds.m0.url: jdbc:mysql://localhost:3306/ds0?serverTimezone=GMT%2B8&euseUnicdoe=true&characterEncoding=utf-8&useSSL=true
spring.ds.m0.username: root
spring.ds.m0.password: root

spring.ds.m1.url: jdbc:mysql://localhost:3306/ds1?serverTimezone=GMT%2B8&euseUnicdoe=true&characterEncoding=utf-8&useSSL=true
spring.ds.m1.username: root
spring.ds.m1.password: root


##sharding-jdbc
# https://shardingsphere.apache.org/document/current/cn/manual/sharding-jdbc/configuration/config-spring-boot/
spring.shardingsphere.enable: true
spring.shardingsphere.props.sql.show: true
